export const ExceptionCode = {
    UNKNOWN_ERROR: { code: 1000, msg: "Unknown error" },
    VALIDATION_ERROR: { code: 1001, msg: "Validation failed" },
    NOT_FOUND: { code: 1002, msg: "Resource not found" },
    UNAUTHORIZED: { code: 1003, msg: "Unauthorized access" },
    FORBIDDEN: { code: 1004, msg: "Forbidden access" },
    CONFLICT: { code: 1005, msg: "Conflict error" },
    BAD_REQUEST: { code: 1006, msg: "Bad request" },
    INTERNAL_SERVER_ERROR: { code: 1007, msg: "Internal server error" },

    RESIDENT_NOT_FOUND: { code: 2000, msg: "Resident not found" },
    USER_NOT_FOUND: { code: 2001, msg: "User not found" },
    USER_ALREADY_EXISTS: { code: 2002, msg: "User already exists" },
    APARTMENT_NOT_FOUND: { code: 2003, msg: "Apartment not found" },
    BUILDING_NOT_FOUND: { code: 2004, msg: "Building not found" },
    BUILDING_ALREADY_EXISTS: { code: 3001, msg: "Building already exists" },
    SERVICE_NOT_FOUND: { code: 2005, msg: "Service not found" },
    CONTRACT_NOT_FOUND: { code: 2006, msg: "Contract not found" },
    INVOICE_NOT_FOUND: { code: 2007, msg: "Invoice not found" },
    PAYMENT_NOT_FOUND: { code: 2008, msg: "Payment not found" },
    SUBSCRIPTION_NOT_FOUND: { code: 2009, msg: "Subscription not found" },
    NOTIFICATION_NOT_FOUND: { code: 2010, msg: "Notification not found" },
    INVOICE_DETAIL_NOT_FOUND: { code: 2011, msg: "Invoice detail not found" },
    SUBSCRIPTION_MISMATCH: { code: 2012, msg: "Subscription does not match apartment and service" },
    APARTMENT_NO_RESIDENT: { code: 2013, msg: "Apartment has no resident assigned" },

    INVALID_PASSWORD: { code: 1008, msg: "Password is incorrect" },
    ACCESS_DENIED: { code: 1009, msg: "Access denied" },
    TOKEN_FAILED: { code: 4000, msg: "Token validation failed" },
    HASHING_FAILED: { code: 4001, msg: "Hashing failed" },
};
