export default {
    moduleFileExtensions: ["js", "json", "ts"],
    rootDir: ".",
    testRegex: ".spec.ts$",
    transform: {
        "^.+\\.(t|j)s$": "ts-jest",
    },
    collectCoverageFrom: [
        "**/*.(t|j)s",
        "!**/main.ts",
        "!**/*.module.ts",
        "!**/jest.config.ts",
        "!**/jest.e2e.config.ts",
        "!**/*.d.ts",
        "!**/node_modules/**",
        "!**/dist/**",
        "!**/coverage/**",
        "!**/test/**",
        "!**/migrations/**",
        "!**/scripts/**",
        "!**/*.config.ts",
        "!**/*.constant.ts",
        "!**/*.enum.ts",
        "!**/*.interface.ts",
        "!**/prisma/**",
        // Exclude infrastructure code patterns
        "!**/strategies/**",
        "!**/filters/**",
        "!**/pipes/**",
        "!**/guards/**",
        "!**/decorators/**",
    ],
    coverageDirectory: "../coverage",
    testEnvironment: "node",
    coverageThreshold: {
        global: {
            statements: 60,
            branches: 50,
            functions: 60,
            lines: 60,
        },
        "./src/**/*.service.ts": {
            statements: 85,
            branches: 75,
            functions: 85,
            lines: 85,
        },
    },
};
